version: "3.8"

x-firmware:
  &firmware
  build: ./firmware/
  image: shop_robotics_firmware
  stdin_open: true
  tty: true
  working_dir: /volume
  #ports:
  #  - "5555:5555" # Pull commands from web interface
  #  - "5556:5556" # Push state to sim (step counts)
  #networks: 
  #   - ar3
  network_mode: host
  volumes:
    - "./firmware:/volume"
  #  - "./firmware/.pio:/root/.pio"
  #  - "./firmware/.packages:/root/.platformio/packages"

x-control:
  &control
  build: ./control/
  image: shop_robotics_control
  working_dir: /volume
  environment:
    - "PYTHONUNBUFFERED=1"
  # networks: 
  #  - ar3
  network_mode: host
  volumes:
    - "./control/:/volume"
  #ports:
  #  - "8000:8000" # Web server
  #  - "8001:8001" # Websocket server

x-sim:
  &sim
  build: ./sim/
  tty: true
  image: shop_robotics_sim
  network_mode: host  
  stop_grace_period: 1s


services:
  fw_native:
    <<: *firmware
    entrypoint: ["bash", "-c", "pio run -e native --silent && .pio/build/native/program"]
    profiles:
     - gamepad
     - headless
     - webots
  fw_native3:
    <<: *firmware
    entrypoint: ["bash", "-c", "pio run -e native3 --silent && .pio/build/native3/program"]
    profiles:
     - headless_tribot
  web_interface3:
    <<: *control
    command: python3 /volume/broker.py -j 3
    profiles:
     - headless_tribot
  web_interface:
    <<: *control
    command: python3 /volume/broker.py
    profiles:
     - gamepad
     - headless
     - webots
  gamepad:
    <<: *control
    command: python3 /volume/gamepad.py
    profiles:
     - gamepad
  stub_robot: # webots_sim not started - does basic, headless simulation
    <<: *sim
    command: /bin/bash -i -c "ros2 run shop_robotics node --ros-args -p stub:=true"
    profiles:
     - gamepad
     - headless
  stub_robot3: # webots_sim not started - does basic, headless simulation
    <<: *sim
    command: /bin/bash -i -c "ros2 run shop_robotics node --ros-args -p stub:=true -p num_j:=3"
    profiles:
     - headless_tribot
  sim_robot:
    <<: *sim
    depends_on:
      - "webots_sim"
    volumes:
      - /tmp:/tmp # Used to sense when webots started
    command: /bin/bash -i -c "ros2 run shop_robotics node"
    profiles:
      - webots
  webots_sim:
    <<: *sim
    stdin_open: true
    runtime: nvidia
    #ports:
    #  - "5557:5557" # Push limit values
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1 # Prevent xcb_shm_attach() errors
      MESA_GL_VERSION_OVERRIDE: 3.3 #https://askubuntu.com/questions/850900/why-is-my-opengl-version-stuck-at-3-0-despite-new-hardware-software 
    volumes:
      - ./sim:/volume
      - ./sim/config:/root/.config/Cyberbotics/
      - /tmp:/tmp
    # entrypoint: bash
    # --stream="port=2000"
    command: /usr/local/webots/webots --batch --mode=realtime /volume/webots/worlds/world.wbt
    profiles:
     - webots

